/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u09208248119
 */
public class JDlgVjrVendedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVjrVendedor
     */
    public JDlgVjrVendedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Vendedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
    public void habilitar(boolean valor){
        jTxtVjrCodigo.setEnabled(valor);
        jTxtVjrNome.setEnabled(valor);
        jFmtVjrCpf.setEnabled(valor);
        jTxtVjrEmail.setEnabled(valor);
        jFmtVjrTelefone.setEnabled(valor);
        jFmtVjrDataContra.setEnabled(valor);
        jFmtVjrComissao.setEnabled(valor);
        jBtnVjrIncluir.setEnabled(!valor);
        jBtnVjrAlterar.setEnabled(!valor);
        jBtnVjrExcluir.setEnabled(!valor);
        jBtnVjrCancelar.setEnabled(valor);
        jBtnVjrConfirmar.setEnabled(valor);
        jBtnVjrPesquisar.setEnabled(!valor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblVjrCodigo = new javax.swing.JLabel();
        jTxtVjrCodigo = new javax.swing.JTextField();
        jLblVjrNome = new javax.swing.JLabel();
        jLblVjrTelefone = new javax.swing.JLabel();
        jLblVjrEmail = new javax.swing.JLabel();
        jLblVjrCpf = new javax.swing.JLabel();
        jLblVjrDataContra = new javax.swing.JLabel();
        jLblVjrComissao = new javax.swing.JLabel();
        jFmtVjrDataContra = new javax.swing.JFormattedTextField();
        jFmtVjrTelefone = new javax.swing.JFormattedTextField();
        jTxtVjrNome = new javax.swing.JTextField();
        jTxtVjrEmail = new javax.swing.JTextField();
        jFmtVjrCpf = new javax.swing.JFormattedTextField();
        jFmtVjrComissao = new javax.swing.JFormattedTextField();
        jBtnVjrIncluir = new javax.swing.JButton();
        jBtnVjrAlterar = new javax.swing.JButton();
        jBtnVjrExcluir = new javax.swing.JButton();
        jBtnVjrCancelar = new javax.swing.JButton();
        jBtnVjrConfirmar = new javax.swing.JButton();
        jBtnVjrPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblVjrCodigo.setText("Código:");

        jLblVjrNome.setText("Nome:");

        jLblVjrTelefone.setText("Telefone:");

        jLblVjrEmail.setText("E-mail:");

        jLblVjrCpf.setText("Cpf:");

        jLblVjrDataContra.setText("Data de contratação:");

        jLblVjrComissao.setText("Comissão:");

        jBtnVjrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnVjrIncluir.setText("Incluir");
        jBtnVjrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrIncluirActionPerformed(evt);
            }
        });

        jBtnVjrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnVjrAlterar.setText("Alterar");
        jBtnVjrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrAlterarActionPerformed(evt);
            }
        });

        jBtnVjrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnVjrExcluir.setText("Excluir");
        jBtnVjrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrExcluirActionPerformed(evt);
            }
        });

        jBtnVjrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnVjrCancelar.setText("Cancelar");
        jBtnVjrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrCancelarActionPerformed(evt);
            }
        });

        jBtnVjrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnVjrConfirmar.setText("Confirmar");
        jBtnVjrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrConfirmarActionPerformed(evt);
            }
        });

        jBtnVjrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnVjrPesquisar.setText("Pesquisar");
        jBtnVjrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLblVjrNome)
                                        .addGap(277, 277, 277))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblVjrTelefone)
                                        .addGap(264, 264, 264))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jFmtVjrTelefone)
                                        .addGap(44, 44, 44)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLblVjrCpf)
                                    .addComponent(jLblVjrEmail)
                                    .addComponent(jFmtVjrCpf, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTxtVjrNome, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 269, Short.MAX_VALUE)
                                    .addComponent(jLblVjrCodigo, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTxtVjrCodigo, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(44, 44, 44)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblVjrDataContra)
                                    .addComponent(jFmtVjrDataContra)
                                    .addComponent(jTxtVjrEmail, javax.swing.GroupLayout.DEFAULT_SIZE, 202, Short.MAX_VALUE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(196, 196, 196)
                        .addComponent(jLblVjrComissao)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtVjrComissao, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jBtnVjrIncluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVjrAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVjrExcluir)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVjrCancelar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVjrConfirmar)
                        .addGap(18, 18, 18)
                        .addComponent(jBtnVjrPesquisar)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrCodigo)
                    .addComponent(jLblVjrDataContra))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrDataContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrNome)
                    .addComponent(jLblVjrEmail))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrTelefone)
                    .addComponent(jLblVjrCpf))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtVjrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrComissao)
                    .addComponent(jFmtVjrComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVjrIncluir)
                    .addComponent(jBtnVjrAlterar)
                    .addComponent(jBtnVjrExcluir)
                    .addComponent(jBtnVjrCancelar)
                    .addComponent(jBtnVjrConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVjrPesquisar))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVjrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnVjrIncluirActionPerformed

    private void jBtnVjrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnVjrAlterarActionPerformed

    private void jBtnVjrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrExcluirActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Confirmar a exclusão?");
    }//GEN-LAST:event_jBtnVjrExcluirActionPerformed

    private void jBtnVjrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnVjrCancelarActionPerformed

    private void jBtnVjrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnVjrConfirmarActionPerformed

    private void jBtnVjrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrPesquisarActionPerformed
        // TODO add your handling code here:
        JOptionPane.showConfirmDialog(null, "Porfavor, informe o código do cliente!");
    }//GEN-LAST:event_jBtnVjrPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrVendedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVjrVendedor dialog = new JDlgVjrVendedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVjrAlterar;
    private javax.swing.JButton jBtnVjrCancelar;
    private javax.swing.JButton jBtnVjrConfirmar;
    private javax.swing.JButton jBtnVjrExcluir;
    private javax.swing.JButton jBtnVjrIncluir;
    private javax.swing.JButton jBtnVjrPesquisar;
    private javax.swing.JFormattedTextField jFmtVjrComissao;
    private javax.swing.JFormattedTextField jFmtVjrCpf;
    private javax.swing.JFormattedTextField jFmtVjrDataContra;
    private javax.swing.JFormattedTextField jFmtVjrTelefone;
    private javax.swing.JLabel jLblVjrCodigo;
    private javax.swing.JLabel jLblVjrComissao;
    private javax.swing.JLabel jLblVjrCpf;
    private javax.swing.JLabel jLblVjrDataContra;
    private javax.swing.JLabel jLblVjrEmail;
    private javax.swing.JLabel jLblVjrNome;
    private javax.swing.JLabel jLblVjrTelefone;
    private javax.swing.JTextField jTxtVjrCodigo;
    private javax.swing.JTextField jTxtVjrEmail;
    private javax.swing.JTextField jTxtVjrNome;
    // End of variables declaration//GEN-END:variables
}
