/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

/**
 *
 * @author u09208248119
 */
public class JDlgVjrCompra extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVjrCompra
     */
    public JDlgVjrCompra(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblVjrCodigo = new javax.swing.JLabel();
        jLblVjrDataCompra = new javax.swing.JLabel();
        jLblVjrFormaPaga = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLblVjrObservacao = new javax.swing.JLabel();
        jLblVjrValorTotal = new javax.swing.JLabel();
        jLblVjrStatus = new javax.swing.JLabel();
        jTxtVjrCodigo = new javax.swing.JTextField();
        jFmtVjrDataCompra = new javax.swing.JFormattedTextField();
        jTxtVjrDesconto = new javax.swing.JTextField();
        jTxtVjrStatus = new javax.swing.JTextField();
        jFmtVjrValorTotal = new javax.swing.JFormattedTextField();
        jFmtVjrFormaPaga = new javax.swing.JFormattedTextField();
        jTxtVjrObervacao = new javax.swing.JTextField();
        jBtnVjrIncluir = new javax.swing.JButton();
        jBtnVjrAlterar = new javax.swing.JButton();
        jBtnVjrExcluir = new javax.swing.JButton();
        jBtnVjrCancelar = new javax.swing.JButton();
        jBtnVjrConfirmar = new javax.swing.JButton();
        jBtnVjrPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblVjrCodigo.setText("Código:");

        jLblVjrDataCompra.setText("Data da Compra:");

        jLblVjrFormaPaga.setText("Forma de Pagamento:");

        jLabel4.setText("Desconto:");

        jLblVjrObservacao.setText("Observação:");

        jLblVjrValorTotal.setText("Valor Total:");

        jLblVjrStatus.setText("Status:");

        jBtnVjrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnVjrIncluir.setText("Incluir");

        jBtnVjrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnVjrAlterar.setText("Alterar");

        jBtnVjrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnVjrExcluir.setText("Excluir");

        jBtnVjrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnVjrCancelar.setText("Cancelar");

        jBtnVjrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnVjrConfirmar.setText("Confirmar");

        jBtnVjrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnVjrPesquisar.setText("Pesquisar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(183, 183, 183)
                .addComponent(jLblVjrObservacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtVjrObervacao, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblVjrCodigo)
                            .addComponent(jLblVjrDataCompra))
                        .addGap(151, 151, 151)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblVjrStatus)
                            .addComponent(jLblVjrValorTotal)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTxtVjrCodigo, javax.swing.GroupLayout.DEFAULT_SIZE, 222, Short.MAX_VALUE)
                            .addComponent(jFmtVjrDataCompra))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jFmtVjrValorTotal, javax.swing.GroupLayout.DEFAULT_SIZE, 208, Short.MAX_VALUE)
                            .addComponent(jTxtVjrStatus))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLblVjrFormaPaga)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jLabel4))
                    .addComponent(jFmtVjrFormaPaga, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addComponent(jTxtVjrDesconto))
                .addGap(68, 68, 68))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jBtnVjrIncluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnVjrAlterar)
                .addGap(18, 18, 18)
                .addComponent(jBtnVjrExcluir)
                .addGap(18, 18, 18)
                .addComponent(jBtnVjrCancelar)
                .addGap(18, 18, 18)
                .addComponent(jBtnVjrConfirmar)
                .addGap(18, 18, 18)
                .addComponent(jBtnVjrPesquisar)
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLblVjrCodigo)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(jLblVjrStatus)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrDesconto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrDataCompra)
                    .addComponent(jLblVjrFormaPaga)
                    .addComponent(jLblVjrValorTotal))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtVjrDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrFormaPaga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrObservacao)
                    .addComponent(jTxtVjrObervacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVjrIncluir)
                    .addComponent(jBtnVjrAlterar)
                    .addComponent(jBtnVjrExcluir)
                    .addComponent(jBtnVjrCancelar)
                    .addComponent(jBtnVjrConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVjrPesquisar))
                .addContainerGap(86, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrCompra.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVjrCompra dialog = new JDlgVjrCompra(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVjrAlterar;
    private javax.swing.JButton jBtnVjrCancelar;
    private javax.swing.JButton jBtnVjrConfirmar;
    private javax.swing.JButton jBtnVjrExcluir;
    private javax.swing.JButton jBtnVjrIncluir;
    private javax.swing.JButton jBtnVjrPesquisar;
    private javax.swing.JFormattedTextField jFmtVjrDataCompra;
    private javax.swing.JFormattedTextField jFmtVjrFormaPaga;
    private javax.swing.JFormattedTextField jFmtVjrValorTotal;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLblVjrCodigo;
    private javax.swing.JLabel jLblVjrDataCompra;
    private javax.swing.JLabel jLblVjrFormaPaga;
    private javax.swing.JLabel jLblVjrObservacao;
    private javax.swing.JLabel jLblVjrStatus;
    private javax.swing.JLabel jLblVjrValorTotal;
    private javax.swing.JTextField jTxtVjrCodigo;
    private javax.swing.JTextField jTxtVjrDesconto;
    private javax.swing.JTextField jTxtVjrObervacao;
    private javax.swing.JTextField jTxtVjrStatus;
    // End of variables declaration//GEN-END:variables
}
