/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import javax.swing.JOptionPane;

/**
 *
 * @author u09208248119
 */
public class JDlgVjrFornecedor extends javax.swing.JDialog {

    /**
     * Creates new form JDlgVjrFornecedor
     */
    public JDlgVjrFornecedor(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        setTitle("Cadastro de Fornecedor");
        setLocationRelativeTo(null);
        habilitar(false);
    }
    
    public void habilitar(boolean valor){
        jTxtVjrCodigo.setEnabled(valor);
        jTxtVjrNomeForne.setEnabled(valor);
        jFmtVjrCnpj.setEnabled(valor);
        jTxtVjrInsEst.setEnabled(valor);
        jTxtVjrEmail.setEnabled(valor);
        jFmtVjrTelefone.setEnabled(valor);
        jFmtVjrCelular.setEnabled(valor);
        jTxtVjrEndereco.setEnabled(valor);
        jFmtVjrNumero.setEnabled(valor);
        jTxtVjrBairro.setEnabled(valor);
        jTxtVjrCidade.setEnabled(valor);
        jTxtVjrEstado.setEnabled(valor);
        jFmtVjrCep.setEnabled(valor);
        jCboVjrStatus.setEnabled(valor);
        jFmtVjrDataCadastro.setEnabled(valor);
        jBtnVjrIncluir.setEnabled(!valor);
        jBtnVjrAlterar.setEnabled(!valor);
        jBtnVjrExcluir.setEnabled(!valor);
        jBtnVjrCancelar.setEnabled(valor);
        jBtnVjrConfirmar.setEnabled(valor);
        jBtnVjrPesquisar.setEnabled(!valor);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblVjrCodigo = new javax.swing.JLabel();
        jTxtVjrCodigo = new javax.swing.JTextField();
        jLblVjrNomeForne = new javax.swing.JLabel();
        jLblVjrCnpj = new javax.swing.JLabel();
        jLblVjrInsEst = new javax.swing.JLabel();
        jTxtVjrNomeForne = new javax.swing.JTextField();
        jFmtVjrCnpj = new javax.swing.JFormattedTextField();
        jTxtVjrInsEst = new javax.swing.JTextField();
        jTxtVjrEmail = new javax.swing.JTextField();
        jLblVjrEmail = new javax.swing.JLabel();
        jLblVjrTelefone = new javax.swing.JLabel();
        jFmtVjrTelefone = new javax.swing.JFormattedTextField();
        jLblVjrCelular = new javax.swing.JLabel();
        jLblVjrEndereco = new javax.swing.JLabel();
        jLblVjrNumero = new javax.swing.JLabel();
        jLblVjrBairro = new javax.swing.JLabel();
        jLblVjrCidade = new javax.swing.JLabel();
        jLblVjrEstado = new javax.swing.JLabel();
        jLblVjrCep = new javax.swing.JLabel();
        jLblVjrDataCada = new javax.swing.JLabel();
        jTxtVjrBairro = new javax.swing.JTextField();
        jTxtVjrEndereco = new javax.swing.JTextField();
        jFmtVjrCep = new javax.swing.JFormattedTextField();
        jTxtVjrCidade = new javax.swing.JTextField();
        jBtnVjrIncluir = new javax.swing.JButton();
        jBtnVjrAlterar = new javax.swing.JButton();
        jBtnVjrExcluir = new javax.swing.JButton();
        jBtnVjrCancelar = new javax.swing.JButton();
        jBtnVjrConfirmar = new javax.swing.JButton();
        jBtnVjrPesquisar = new javax.swing.JButton();
        jCboVjrStatus = new javax.swing.JCheckBox();
        jFmtVjrCelular = new javax.swing.JFormattedTextField();
        jFmtVjrNumero = new javax.swing.JFormattedTextField();
        jTxtVjrEstado = new javax.swing.JTextField();
        jFmtVjrDataCadastro = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLblVjrCodigo.setText("Código:");

        jLblVjrNomeForne.setText("Nome do Fornecedor:");

        jLblVjrCnpj.setText("CNPJ:");

        jLblVjrInsEst.setText("Inscrição Estadual:");

        jLblVjrEmail.setText("E-mail:");

        jLblVjrTelefone.setText("Telefone:");

        jLblVjrCelular.setText("Celular:");

        jLblVjrEndereco.setText("Endereço:");

        jLblVjrNumero.setText("Numero (Logradouro):");

        jLblVjrBairro.setText("Bairro:");

        jLblVjrCidade.setText("Cidade:");

        jLblVjrEstado.setText("Estado:");

        jLblVjrCep.setText("Cep:");

        jLblVjrDataCada.setText("Data de Cadastro:");

        jBtnVjrIncluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnVjrIncluir.setText("Incluir");
        jBtnVjrIncluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrIncluirActionPerformed(evt);
            }
        });

        jBtnVjrAlterar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnVjrAlterar.setText("Alterar");
        jBtnVjrAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrAlterarActionPerformed(evt);
            }
        });

        jBtnVjrExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnVjrExcluir.setText("Excluir");
        jBtnVjrExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrExcluirActionPerformed(evt);
            }
        });

        jBtnVjrCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnVjrCancelar.setText("Cancelar");
        jBtnVjrCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrCancelarActionPerformed(evt);
            }
        });

        jBtnVjrConfirmar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnVjrConfirmar.setText("Confirmar");
        jBtnVjrConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrConfirmarActionPerformed(evt);
            }
        });

        jBtnVjrPesquisar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnVjrPesquisar.setText("Pesquisar");
        jBtnVjrPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnVjrPesquisarActionPerformed(evt);
            }
        });

        jCboVjrStatus.setText("Ativo");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblVjrCodigo)
                            .addComponent(jTxtVjrCodigo)
                            .addComponent(jLblVjrNomeForne)
                            .addComponent(jLblVjrCnpj)
                            .addComponent(jLblVjrInsEst)
                            .addComponent(jTxtVjrNomeForne, javax.swing.GroupLayout.DEFAULT_SIZE, 227, Short.MAX_VALUE)
                            .addComponent(jFmtVjrCnpj)
                            .addComponent(jTxtVjrInsEst)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(jBtnVjrIncluir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                        .addComponent(jBtnVjrAlterar)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLblVjrEmail)
                            .addComponent(jTxtVjrEmail)
                            .addComponent(jLblVjrTelefone)
                            .addComponent(jFmtVjrTelefone)
                            .addComponent(jLblVjrCelular)
                            .addComponent(jLblVjrDataCada)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(16, 16, 16)
                                .addComponent(jBtnVjrExcluir)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 37, Short.MAX_VALUE)
                                .addComponent(jBtnVjrCancelar)
                                .addGap(30, 30, 30))
                            .addComponent(jFmtVjrCelular)
                            .addComponent(jFmtVjrDataCadastro))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLblVjrBairro)
                                    .addComponent(jLblVjrEndereco)
                                    .addComponent(jTxtVjrEndereco)
                                    .addComponent(jTxtVjrBairro)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLblVjrCidade)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jLblVjrEstado)
                                        .addGap(36, 36, 36))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLblVjrNumero)
                                            .addGroup(layout.createSequentialGroup()
                                                .addGap(1, 1, 1)
                                                .addComponent(jFmtVjrNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLblVjrCep)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                            .addComponent(jFmtVjrCep, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)))))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jBtnVjrConfirmar)
                                        .addGap(18, 18, 18)
                                        .addComponent(jBtnVjrPesquisar))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTxtVjrCidade, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jTxtVjrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jCboVjrStatus)))
                .addContainerGap(74, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrCodigo)
                    .addComponent(jLblVjrDataCada)
                    .addComponent(jLblVjrEndereco))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrEndereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrDataCadastro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrNomeForne)
                    .addComponent(jLblVjrEmail)
                    .addComponent(jLblVjrBairro))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrNomeForne, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrCnpj)
                    .addComponent(jLblVjrTelefone)
                    .addComponent(jLblVjrNumero)
                    .addComponent(jLblVjrCep))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFmtVjrCnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLblVjrInsEst)
                    .addComponent(jLblVjrCelular)
                    .addComponent(jLblVjrCidade)
                    .addComponent(jLblVjrEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTxtVjrInsEst, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jFmtVjrCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTxtVjrEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jCboVjrStatus)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnVjrIncluir)
                    .addComponent(jBtnVjrAlterar)
                    .addComponent(jBtnVjrExcluir)
                    .addComponent(jBtnVjrCancelar)
                    .addComponent(jBtnVjrConfirmar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnVjrPesquisar))
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jBtnVjrIncluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrIncluirActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnVjrIncluirActionPerformed

    private void jBtnVjrAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrAlterarActionPerformed
        // TODO add your handling code here:
        habilitar(true);
    }//GEN-LAST:event_jBtnVjrAlterarActionPerformed

    private void jBtnVjrExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrExcluirActionPerformed
        // TODO add your handling code here:
         JOptionPane.showConfirmDialog(null, "A exclusão não poderá ser desfeita.", JOptionPane.YES_NO_OPTION);
    }//GEN-LAST:event_jBtnVjrExcluirActionPerformed

    private void jBtnVjrCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrCancelarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnVjrCancelarActionPerformed

    private void jBtnVjrConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrConfirmarActionPerformed
        // TODO add your handling code here:
        habilitar(false);
    }//GEN-LAST:event_jBtnVjrConfirmarActionPerformed

    private void jBtnVjrPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnVjrPesquisarActionPerformed
        // TODO add your handling code here:
          JOptionPane.showInputDialog(null, "Informe o código do Cliente:");
    }//GEN-LAST:event_jBtnVjrPesquisarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVjrFornecedor.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVjrFornecedor dialog = new JDlgVjrFornecedor(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnVjrAlterar;
    private javax.swing.JButton jBtnVjrCancelar;
    private javax.swing.JButton jBtnVjrConfirmar;
    private javax.swing.JButton jBtnVjrExcluir;
    private javax.swing.JButton jBtnVjrIncluir;
    private javax.swing.JButton jBtnVjrPesquisar;
    private javax.swing.JCheckBox jCboVjrStatus;
    private javax.swing.JFormattedTextField jFmtVjrCelular;
    private javax.swing.JFormattedTextField jFmtVjrCep;
    private javax.swing.JFormattedTextField jFmtVjrCnpj;
    private javax.swing.JFormattedTextField jFmtVjrDataCadastro;
    private javax.swing.JFormattedTextField jFmtVjrNumero;
    private javax.swing.JFormattedTextField jFmtVjrTelefone;
    private javax.swing.JLabel jLblVjrBairro;
    private javax.swing.JLabel jLblVjrCelular;
    private javax.swing.JLabel jLblVjrCep;
    private javax.swing.JLabel jLblVjrCidade;
    private javax.swing.JLabel jLblVjrCnpj;
    private javax.swing.JLabel jLblVjrCodigo;
    private javax.swing.JLabel jLblVjrDataCada;
    private javax.swing.JLabel jLblVjrEmail;
    private javax.swing.JLabel jLblVjrEndereco;
    private javax.swing.JLabel jLblVjrEstado;
    private javax.swing.JLabel jLblVjrInsEst;
    private javax.swing.JLabel jLblVjrNomeForne;
    private javax.swing.JLabel jLblVjrNumero;
    private javax.swing.JLabel jLblVjrTelefone;
    private javax.swing.JTextField jTxtVjrBairro;
    private javax.swing.JTextField jTxtVjrCidade;
    private javax.swing.JTextField jTxtVjrCodigo;
    private javax.swing.JTextField jTxtVjrEmail;
    private javax.swing.JTextField jTxtVjrEndereco;
    private javax.swing.JTextField jTxtVjrEstado;
    private javax.swing.JTextField jTxtVjrInsEst;
    private javax.swing.JTextField jTxtVjrNomeForne;
    // End of variables declaration//GEN-END:variables
}
