/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author u09208248119
 */
public class JFrmVjrPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmVjrPrincipal
     */
    public JFrmVjrPrincipal() {
        initComponents();
        setTitle("Sistema de Compra e Venda de bebidas");
        setLocationRelativeTo(null);
        setExtendedState(MAXIMIZED_BOTH);
    }
    
   

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuVjrCadastro = new javax.swing.JMenu();
        jMnuVjrUsuario = new javax.swing.JMenuItem();
        jMnuVjrClientes = new javax.swing.JMenuItem();
        jMnuVjrProdutos = new javax.swing.JMenuItem();
        jMnuVjrVendedor = new javax.swing.JMenuItem();
        jMnuVjrFornecedor = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuVjrSair = new javax.swing.JMenuItem();
        jMnuVjrMovimento = new javax.swing.JMenu();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuItem8 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMnuVjrCadastro.setText("Cadastro");

        jMnuVjrUsuario.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuVjrUsuario.setText("Usuário");
        jMnuVjrUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrUsuarioActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrUsuario);

        jMnuVjrClientes.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuVjrClientes.setText("Clientes");
        jMnuVjrClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrClientesActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrClientes);

        jMnuVjrProdutos.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrProdutos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuVjrProdutos.setText("Produtos");
        jMnuVjrProdutos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrProdutosActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrProdutos);

        jMnuVjrVendedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrVendedor.setText("Vendedor");
        jMnuVjrVendedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrVendedorActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrVendedor);

        jMnuVjrFornecedor.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_F, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrFornecedor.setText("Fornecedor");
        jMnuVjrFornecedor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrFornecedorActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrFornecedor);
        jMnuVjrCadastro.add(jSeparator1);

        jMnuVjrSair.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMnuVjrSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuVjrSair.setText("Sair");
        jMnuVjrSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVjrSairActionPerformed(evt);
            }
        });
        jMnuVjrCadastro.add(jMnuVjrSair);

        jMenuBar1.add(jMnuVjrCadastro);

        jMnuVjrMovimento.setText("Movimento");

        jMenuItem4.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem4.setText("Compra");
        jMnuVjrMovimento.add(jMenuItem4);

        jMenuItem5.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_DOWN_MASK));
        jMenuItem5.setText("Venda");
        jMnuVjrMovimento.add(jMenuItem5);

        jMenuItem6.setText("Compra_produto");
        jMnuVjrMovimento.add(jMenuItem6);

        jMenuItem8.setText("Venda_produto");
        jMnuVjrMovimento.add(jMenuItem8);

        jMenuBar1.add(jMnuVjrMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 618, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuVjrUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrUsuarioActionPerformed
        // TODO add your handling code here:
        JDlgVjrUsuario jDlgVjrUsuario = new JDlgVjrUsuario(null, true);
        jDlgVjrUsuario.setVisible(true);
    }//GEN-LAST:event_jMnuVjrUsuarioActionPerformed

    private void jMnuVjrClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrClientesActionPerformed
        // TODO add your handling code here:
        JDlgVjrCliente jDlgVjrCliente = new JDlgVjrCliente(null,true);
        jDlgVjrCliente.setVisible(true);
    }//GEN-LAST:event_jMnuVjrClientesActionPerformed

    private void jMnuVjrProdutosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrProdutosActionPerformed
        // TODO add your handling code here:
        JDlgVjrBebida jDlgVjrBebida = new JDlgVjrBebida(null,true);
        jDlgVjrBebida.setVisible(true);
    }//GEN-LAST:event_jMnuVjrProdutosActionPerformed

    private void jMnuVjrVendedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrVendedorActionPerformed
        // TODO add your handling code here:
        JDlgVjrVendedor jDlgVjrVendedor = new JDlgVjrVendedor(null, true);
        jDlgVjrVendedor.setVisible(true);
    }//GEN-LAST:event_jMnuVjrVendedorActionPerformed

    private void jMnuVjrFornecedorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrFornecedorActionPerformed
        // TODO add your handling code here:
        JDlgVjrFornecedor jDlgVjrFornecedor = new JDlgVjrFornecedor(null,true);
        jDlgVjrFornecedor.setVisible(true);
    }//GEN-LAST:event_jMnuVjrFornecedorActionPerformed

    private void jMnuVjrSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVjrSairActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuVjrSairActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmVjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmVjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmVjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmVjrPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmVjrPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenu jMnuVjrCadastro;
    private javax.swing.JMenuItem jMnuVjrClientes;
    private javax.swing.JMenuItem jMnuVjrFornecedor;
    private javax.swing.JMenu jMnuVjrMovimento;
    private javax.swing.JMenuItem jMnuVjrProdutos;
    private javax.swing.JMenuItem jMnuVjrSair;
    private javax.swing.JMenuItem jMnuVjrUsuario;
    private javax.swing.JMenuItem jMnuVjrVendedor;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
